

name: Testes CI
#Gatilhos
#Gatilhos programados -> ou acionados por eventos
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  #Maquina ou abimiente
    runs-on: ubuntu-latest

    steps:
    #download do codigo
    - uses: actions/checkout@v2
    #setup versao do node
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        
    - run: npm install
    
    - run: npm run cy:run
      continue-on-error: true
      
    - run: npm run report:merg
    
    - run: npm run report:mocha
    
    #Git Hub Pages -> publicar o relatorio
    - name: Deploy to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: JamesIves/github-pages-deploy-action@830e6a4f7c81743c52f3fed0ac67428feff9620a
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDERS: mochawesome-report
